### ISSUE TITLE
[DOC] Host documentation on GitHub Pages

### ISSUE THREAD

**Issue by tbouffard** [process-analytics/bpmn-visualization-R#19]
see
- https://www.rostrum.blog/2020/08/09/ghactions-pkgs/#example-r2eng-package
- https://pkgdown.r-lib.org/

Generate and deploy the site with GitHub actions
- see https://pkgdown.r-lib.org/articles/pkgdown.html#publishing
  - https://github.com/matt-dray/r2eng/blob/master/.github/workflows/pkgdown.yaml
  - https://github.com/cynkra/dm/blob/main/.github/workflows/pkgdown.yaml

**Tasks**

- [x] Configure the repository: we are going to use GH Actions to publish (no branch) like done in 
- [x] Configure the GH workflow
- [x] Add the url to the repo settings on GH
- [x] Display the environment in the repository home
- [x] Once deployed, promote the site in the package DESCRIPTION file. See https://pkgdown.r-lib.org/articles/pkgdown.html#promoting

![image](https://user-images.githubusercontent.com/27200110/204328832-7e546004-3f3b-4db5-954d-c6d123eb0ff7.png)
