### ISSUE TITLE
[DOC] Explain how to install

### ISSUE THREAD

**Issue by tbouffard** [process-analytics/bpmn-visualization-R#20]
From CRAN: #10 
From GitHub for latest unreleased/development version or for alternative

See https://cynkra.github.io/dm/#installation for instance

![image](https://user-images.githubusercontent.com/27200110/130771345-eac5abb5-ae7f-4194-aa7d-168e00b9547f.png)

https://www.rdocumentation.org/packages/remotes/versions/2.4.0/topics/install_github

- [x] Install from github while no package available on CRAN #21
- [x] install from github for development #70
- [x] install from github with a specific tagged version #70
