### ISSUE TITLE
[INFRA] Stop automatically announcing new versions on Twitter

### ISSUE THREAD

**Issue by tbouffard** [process-analytics/bpmn-visualization-R#239]
**Rationale**: see https://github.com/process-analytics/bpmn-visualization-js/issues/2676

```[tasklist]
### Tasks
- [x] Remove the twitter secrets from the repository
- [x] Remove the tweet from the announce workflow
- [x] Update the release procedure to send the tweet manually
```
