### ISSUE TITLE
[DOC] Document how to create the image of the README

### ISSUE THREAD

**Issue by tbouffard** [process-analytics/bpmn-visualization-R#251]
Today, we have an image in the README that we update manually.

The script used to create it is not documented in the repository and is only available in the description of Pull Requests. This is not easy to remind and there is a risk of information lost:
- #45 
- #72 

Notice that #247 add some style updates that are not documented in existing script (the SVG file was edited manually).

We should put the script in the doc folder instead of keeping it in comments of Pull Requests and probably rename this folder into docs for consistency with other repositories.

Notice that the image currently displayed in the README has been updated manually to be stored as SVG
This is because the SVG content in a webpage contains foreignObject to display the label, and the foreignObject are often not displayed correctly in non browser SVG viewer. For more details, see https://github.com/process-analytics/bpmn-visualization-js/issues/320.

We could avoid to edit the SVG to manage the label positioning by using https://github.com/process-analytics/bpmn-visualization-tools/tree/v0.4.0/bpmn-visualization-svg-screenshots.

```[tasklist]
### Tasks
- [ ] Provide the R script that can generate the image as it is today (including style update of some elements)
- [ ] Rename the `doc` folder into `docs` for consistency with other repositories. Don't forget to update `.Rbuildignore`
- [ ] Document how to extract the SVG
- [ ] https://github.com/process-analytics/bpmn-visualization-R/issues/84
- [ ] https://github.com/process-analytics/bpmn-visualization-R/issues/252
```
