### ISSUE TITLE
[INFRA] Automate tag and files update

### ISSUE THREAD

**Issue by tbouffard** [process-analytics/bpmn-visualization-R#47]
Currently (in v0.2.1), the version must be updated prior and after releasing (by creating a PR). This is painful and error prone
The git tag is created only when the GitHub release is published.

I suggest we do something like for the bpmn-visualization TypeScript library.
We provide a GitHub workflow that will do everything for us:
- It takes as an input the version to release.
- it updates the files with the new version and commit
- then it creates the related tag
- then it updates the files with the development version and commit
- finally, it push the changes and the tag

If possible, the development version should be automatically computed by the workflow to avoid human error

### Tasks to do

Add a Github workflow triggered by `workflow_dispatch` (manual run)
- [x] pass the new version
- [x] update the files containing the version accordingly (see MAINTAINERS.md)
- [x] create the git tag
- [x] set the development version accordingly (see MAINTAINERS.md)
- [x] push all commits and the tag

Documentation
- [x] update MAINTAINERS.md to explain the new release process

### Notes
- remember that the GH_TOKEN has readonly permissions by default
- check how we proceed in the bpmn-visualization-js repo
- don't forget to use the playground repository for testing
